jobs:
- job: ${{ parameters.JobName }}
  timeoutInMinutes: 90
  pool:
    name: Azure Pipelines
    vmImage: ${{ parameters.VmImage }}

  steps:
    - task: PowerShell@2
      displayName: 'Build Python $(VERSION)'
      inputs:
        targetType: filePath
        filePath: 'python/scripts/nix-prebuild.ps1'
        arguments: '-Version $(ToolVersion) -Architecture $(Architecture) -DestinationPath $(Build.BinariesDirectory) -Platform $(Platform)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: Python $(VERSION)'
      inputs:
        PathtoPublish: '$(Build.BinariesDirectory)'
        ArtifactName: '$(ToolName)-$(ToolVersion)-$(Architecture)-$(Platform)'
