name: Python $(VERSION) (x64)

trigger: none

variables:
  VmImage: 'vs2017-win2016'
  ToolVersion: '$(VERSION)'
  ToolName: python
  Platform: windows
  Architecture: x64

jobs:
- template: /python/templates/windows-VS2017/build_job.yml
  parameters:
    VmImage: $(VmImage)
    JobName: Build_Python_X64_Windows

- template: /python/tests/test_job.yml
  parameters:
    VmImage: $(VmImage)
    JobName: Test_Python_x64_Windows
    DependsOn: Build_Python_X64_Windows
